language: minimal
os: linux

# Integration tests need to run first to reset the PR build status to pending
stages:
  - 'Trigger Integration Tests'
  - 'SourceClear and Lint'
  - 'Unit Tests'

jobs:
  include:
    - stage: 'Trigger Integration Tests'
      language: minimal
      os: linux
      env:
        - SDK=objective-c
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - TESTAPP_TAG=master
      cache: false
      before_install: skip
      install: skip
      before_script:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"
      after_success: travis_terminate 0

    - stage: 'SourceClear and Lint'
      language: objective-c
      os: osx
      addons:
        srcclr: true
      install: gem install cocoapods
      script:
        - pod spec lint --quick

    - &unittests
      stage: 'Unit Tests'
      language: objective-c
      name: 'Unit Testing With Multi-Simulators'
      os: osx
      osx_image: xcode10
      before_install:
        - gem install slather --no-rdoc --no-ri --no-document --quiet
      script:
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait ./Scripts/test_all.sh &> buildoutput; fi
        - more buildoutput | xcpretty -c
      after_success:
        - slather
        - sleep 5 # https://github.com/travis-ci/travis-ci/issues/4725
